# Send this build to the travis.ci container-based infrastructure
# which typically has more capacity than the open-source Linux pool
sudo: false
# Tell Travis you want a Python environment to test in
language: python
# List the versions of Python you'd like to test against
services:
  - postgresql
env:
  global:
    - DJANGO_SETTINGS_MODULE=tests.settings
  matrix:
    - DJANGO_VERSION=1.8.19
    - DJANGO_VERSION=1.9.13
    - DJANGO_VERSION=1.10.8
    - DJANGO_VERSION=1.11.18
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# Tell it the things it will need to install when it boots
install:
 - pip install -q pytz coveralls flake8 psycopg2
 - pip install -q "Django==$DJANGO_VERSION"
 - pip install -e .
# Tell Travis how to run the test script itself
before_script:
  - psql -c 'create database naivedatetimefield;' -U postgres
script:
  - flake8 naivedatetimefield/
  - coverage run --parallel-mode --source=naivedatetimefield runtests.py
  - coverage combine
after_success: coveralls
